# fly.toml app configuration file generated for book-reading-backend on 2024-02-08T21:58:16+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'book-reading-backend'
primary_region = 'nrt'

[build]
  builder = 'paketobuildpacks/builder:base'

  [build.args]
    BPE_APPEND_JAVA_TOOL_OPTIONS = '-XX:ReservedCodeCacheSize=30M -Xss256k'
    BPE_BPL_JVM_THREAD_COUNT = '30'
    BPE_DELIM_JAVA_TOOL_OPTIONS = ' '
    BPE_SERVER_TOMCAT_THREADS_MAX = '10'
    BP_JVM_VERSION = '17'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
